// tests/test_pipeline.cpp — end-to-end pipeline tests
//
// These tests run the full pipeline (lex -> parse -> resolve -> check
// -> borrow -> emit LLVM IR) on small programs and verify the output
// contains expected LLVM IR constructs.

#include "test_framework.hpp"

#include "ast/printer.hpp"
#include "borrow/borrow.hpp"
#include "check/check.hpp"
#include "diagnostics/diagnostics.hpp"
#include "lexer/lexer.hpp"
#include "llvm/emit.hpp"
#include "parser/parser.hpp"
#include "resolve/resolve.hpp"
#include "support/arena.hpp"
#include "support/intern.hpp"
#include "support/source.hpp"
#include "types/types.hpp"

#include <string>
#include <string_view>

using namespace tether;
using namespace tether::type;

static std::string compile_to_llvm(const std::string& src) {
    InternTable       intern;
    DiagnosticEmitter diag;
    SourceManager     sm;
    Arena             arena;
    TypeContext       tc(arena, intern);

    uint32_t fid = sm.load_buffer("<test>", src);
    const SourceFile& f = sm.file(fid);
    Lexer lexer(intern, diag, f);
    auto tokens = lexer.tokenize();
    Parser parser(intern, diag, sm, arena, std::move(tokens));
    auto m = parser.parse_module();

    resolve::Resolver resolver(tc, diag, intern, arena);
    resolver.resolve_module(*m);
    check::TypeChecker checker(tc, diag, resolver, intern);
    checker.check_module(*m);
    borrow::BorrowChecker borrow(tc, diag, resolver, intern);
    borrow.check_module(*m);

    llvm::Emitter emitter(tc, diag, intern, arena);
    return emitter.emit_module(*m);
}

TETHER_TEST(emit_empty_module) {
    std::string ir = compile_to_llvm("module test");
    TETHER_CHECK(ir.find("; Module generated by tetherc") != std::string::npos);
    TETHER_CHECK(ir.find("Source module: test") != std::string::npos);
}

TETHER_TEST(emit_simple_fn) {
    std::string ir = compile_to_llvm(
        "fn answer() -> i32 { return 42 }");
    TETHER_CHECK(ir.find("define") != std::string::npos);
    TETHER_CHECK(ir.find("@_tether_answer") != std::string::npos);
    TETHER_CHECK(ir.find("ret i64") != std::string::npos);
    TETHER_CHECK(ir.find("42") != std::string::npos);
}

TETHER_TEST(emit_arithmetic) {
    std::string ir = compile_to_llvm(
        "fn add(a: i32, b: i32) -> i32 { return a + b }");
    TETHER_CHECK(ir.find("@_tether_add") != std::string::npos);
    TETHER_CHECK(ir.find("add i64") != std::string::npos);
}

TETHER_TEST(emit_extern_decl) {
    std::string ir = compile_to_llvm(
        "extern fn printf(fmt: *const u8, ...) -> int");
    TETHER_CHECK(ir.find("declare") != std::string::npos);
    TETHER_CHECK(ir.find("@printf") != std::string::npos);
    TETHER_CHECK(ir.find("...") != std::string::npos);
}

TETHER_TEST(emit_string_literal) {
    std::string ir = compile_to_llvm(
        "fn greet() { printf(\"hello\") }");
    TETHER_CHECK(ir.find("@.str.") != std::string::npos);
    TETHER_CHECK(ir.find("hello") != std::string::npos);
    TETHER_CHECK(ir.find("private unnamed_addr constant") != std::string::npos);
}

TETHER_TEST(emit_if_else) {
    std::string ir = compile_to_llvm(
        "fn abs(x: i32) -> i32 {"
        "  if x < 0 { return 0 - x } else { return x }"
        "}");
    TETHER_CHECK(ir.find("br i1") != std::string::npos);
    TETHER_CHECK(ir.find("label %") != std::string::npos);
}

TETHER_TEST(emit_while_loop) {
    std::string ir = compile_to_llvm(
        "fn count() { let i = 0; while i < 10 { i = i + 1 } }");
    TETHER_CHECK(ir.find("br label %") != std::string::npos);
    TETHER_CHECK(ir.find("icmp slt") != std::string::npos);
}

TETHER_TEST(emit_struct_type) {
    std::string ir = compile_to_llvm(
        "struct Point { x: i32, y: i32 }");
    TETHER_CHECK(ir.find("%struct.Point") != std::string::npos);
    TETHER_CHECK(ir.find("= type {") != std::string::npos);
}

TETHER_TEST(borrow_checker_catches_double_move) {
    InternTable       intern;
    DiagnosticEmitter diag;
    SourceManager     sm;
    Arena             arena;
    TypeContext       tc(arena, intern);

    uint32_t fid = sm.load_buffer("<test>",
        "fn f() { let x = 1; let y = move x; let z = move x }");
    const SourceFile& f = sm.file(fid);
    Lexer lexer(intern, diag, f);
    auto tokens = lexer.tokenize();
    Parser parser(intern, diag, sm, arena, std::move(tokens));
    auto m = parser.parse_module();
    resolve::Resolver resolver(tc, diag, intern, arena);
    resolver.resolve_module(*m);
    borrow::BorrowChecker borrow(tc, diag, resolver, intern);
    borrow.check_module(*m);
    TETHER_CHECK(diag.has_errors());
    std::string rendered = diag.render(sm);
    TETHER_CHECK(rendered.find("use of moved value") != std::string::npos);
}

TETHER_TEST(borrow_checker_catches_mut_while_shared) {
    InternTable       intern;
    DiagnosticEmitter diag;
    SourceManager     sm;
    Arena             arena;
    TypeContext       tc(arena, intern);

    uint32_t fid = sm.load_buffer("<test>",
        "fn f() { let x = 1; let a = borrow x; let b = borrow mut x }");
    const SourceFile& f = sm.file(fid);
    Lexer lexer(intern, diag, f);
    auto tokens = lexer.tokenize();
    Parser parser(intern, diag, sm, arena, std::move(tokens));
    auto m = parser.parse_module();
    resolve::Resolver resolver(tc, diag, intern, arena);
    resolver.resolve_module(*m);
    borrow::BorrowChecker borrow(tc, diag, resolver, intern);
    borrow.check_module(*m);
    TETHER_CHECK(diag.has_errors());
    std::string rendered = diag.render(sm);
    TETHER_CHECK(rendered.find("cannot take mutable borrow") !=
                 std::string::npos);
}
