// llvm/emit.cpp — LLVM IR text emitter implementation

#include "llvm/emit.hpp"

#include <sstream>
#include <string>
#include <string_view>

namespace tether::llvm {

using namespace tether::ast;
using namespace tether::type;

std::string Emitter::emit_module(const ast::Module& m) {
    out_.clear();
    out_ += "; Module generated by tetherc v0.2\n";
    out_ += "; Source module: ";
    for (size_t i = 0; i < m.module_path.size(); ++i) {
        if (i) out_ += "::";
        out_ += intern_.get(m.module_path[i]);
    }
    out_ += "\n\n";

    // Emit string literal globals (collected during emission).
    // We do a first pass over the AST to collect them, then emit.
    // For v0.2 we emit them inline as we encounter them, and they
    // appear at the top of the file because we emit them into a
    // separate buffer.

    std::string items;
    std::string saved_out = out_;
    out_ = items;
    for (ItemPtr item : m.items) {
        if (item) emit_item(*item);
    }
    items = out_;
    out_ = saved_out;

    // Emit string globals.
    for (const auto& [sid, name] : strings_) {
        std::string_view text = intern_.get(sid);
        out_ += name;
        out_ += " = private unnamed_addr constant [";
        out_ += std::to_string(text.size() + 1);
        out_ += " x i8] c\"";
        for (char c : text) {
            if (c == '\\' || c == '"') { out_ += '\\'; out_ += c; }
            else if (c >= 32 && c < 127) { out_ += c; }
            else {
                char buf[8];
                std::snprintf(buf, sizeof(buf), "\\%02X",
                              static_cast<unsigned char>(c));
                out_ += buf;
            }
        }
        out_ += "\\00\"\n";
    }
    if (!strings_.empty()) out_ += "\n";

    // Emit all items.
    out_ += items;
    return out_;
}

void Emitter::emit_item(const ast::Item& item) {
    switch (item.kind) {
        case ItemKind::Fn:
            emit_fn(item, /*is_decl=*/false);
            break;
        case ItemKind::Extern:
            if (item.extern_decl) {
                emit_fn(*item.extern_decl, /*is_decl=*/true);
            }
            break;
        case ItemKind::Struct:
            emit_struct_type(item);
            break;
        case ItemKind::Enum:
        case ItemKind::Union:
            // Lower as opaque structs for v0.2.
            {
                std::string name = std::string(intern_.get(item.name));
                out_ += "%struct.";
                out_ += name;
                out_ += " = type opaque\n";
            }
            break;
        case ItemKind::Trait:
        case ItemKind::Impl:
            // Emit impl members as standalone functions.
            for (ItemPtr m : item.impl_members) {
                if (m) emit_fn(*m, /*is_decl=*/false);
            }
            break;
        case ItemKind::TypeAlias:
        case ItemKind::Const:
        case ItemKind::Static:
            // v0.2: skip; these will be handled when the SSA layer
            // lands.
            break;
        case ItemKind::Module:
        case ItemKind::Import:
        case ItemKind::Rewrite:
        case ItemKind::Macro:
        case ItemKind::Export:
            if (item.inner) emit_item(*item.inner);
            break;
    }
}

void Emitter::emit_struct_type(const ast::Item& item) {
    std::string name = std::string(intern_.get(item.name));
    out_ += "%struct.";
    out_ += name;
    out_ += " = type { ";
    if (item.fields.empty()) {
        out_ += "i8"; // opaque struct placeholder
    } else {
        for (size_t i = 0; i < item.fields.size(); ++i) {
            if (i) out_ += ", ";
            // Field types are resolved by the type checker; for v0.2
            // we emit them as opaque pointers if we can't resolve.
            out_ += "i64"; // placeholder
        }
    }
    out_ += " }\n";
}

void Emitter::emit_fn(const ast::Item& item, bool is_decl) {
    reset_function_state();

    std::string name = std::string(intern_.get(item.name));
    std::string mangled = is_decl ? name : ("_tether_" + name);

    // Resolve return type.
    type::TypePtr ret_type = nullptr;
    if (item.return_type) {
        if (!item.return_type->path.empty()) {
            ret_type = tc_.lookup_primitive(intern_.get(item.return_type->path[0]));
        }
        if (!ret_type && item.return_type->base) {
            if (!item.return_type->base->path.empty()) {
                auto base = tc_.lookup_primitive(intern_.get(item.return_type->base->path[0]));
                if (base) {
                    if (item.return_type->kind == ast::TypeKind::Ref ||
                        item.return_type->kind == ast::TypeKind::BorrowRef) {
                        ret_type = tc_.make_ref(base, item.return_type->is_mut);
                    } else if (item.return_type->kind == ast::TypeKind::RawPtr) {
                        ret_type = tc_.make_raw_ptr(base, item.return_type->is_mut);
                    }
                }
            }
        }
        if (!ret_type) ret_type = tc_.i64();
    } else {
        ret_type = tc_.void_type();
    }
    // For v0.2, all integer types lower to i64 for uniformity. This
    // avoids the need for sign/zero extensions at call boundaries.
    // A future version will use the actual bit widths.
    if (tc_.is_integer(ret_type)) {
        ret_type = tc_.i64();
    }
    std::string ret_ty = tc_.render_llvm(ret_type);

    // For declarations, emit the signature.
    if (is_decl) {
        std::string sig;
        sig += "declare ";
        sig += ret_ty;
        sig += " @";
        sig += name;
        sig += "(";
        for (size_t i = 0; i < item.params.size(); ++i) {
            if (i) sig += ", ";
            if (item.params[i].is_variadic) {
                sig += "...";
            } else {
                // v0.2: all params are i64.
                sig += "i64";
            }
        }
        sig += ")\n";
        out_ += sig;
        return;
    }

    // Definition.
    current_ret_type_ = ret_type;
    std::string sig;
    sig += "define ";
    sig += ret_ty;
    sig += " @";
    sig += mangled;
    sig += "(";
    for (size_t i = 0; i < item.params.size(); ++i) {
        if (i) sig += ", ";
        sig += "i64";
        sig += " %arg";
        sig += std::to_string(i);
        StrId pname = item.params[i].name;
        if (pname != kInvalidStrId) {
            LocalSlot slot;
            slot.alloca_name = "%arg" + std::to_string(i);
            slot.type = tc_.i64();
            locals_[pname] = slot;
        }
    }
    sig += ") {\n";
    sig += "entry:\n";

    body_.clear();
    terminated_ = false;

    if (item.body) {
        (void)emit_block(item.body);
    }

    if (!terminated_) {
        if (tc_.is_void(ret_type)) {
            body_ += "  ret void\n";
        } else {
            body_ += "  ret " + ret_ty + " 0\n";
        }
    }

    out_ += sig;
    out_ += entry_allocas_;
    out_ += body_;
    out_ += "}\n\n";
}

std::string Emitter::emit_block(ast::BlockPtr b) {
    if (!b) return "";
    for (StmtPtr s : b->stmts) {
        emit_stmt(s);
    }
    if (b->trailing) {
        return emit_expr(b->trailing);
    }
    return "";
}

void Emitter::emit_stmt(StmtPtr s) {
    if (!s || terminated_) return;
    switch (s->kind) {
        case StmtKind::Let: {
            // For v0.2, we don't emit allocas for let bindings — we
            // just emit the value expression and remember its SSA
            // register under the binding name. This works because
            // v0.2 doesn't support mutation or shadowing.
            if (s->let_value && s->let_name != kInvalidStrId) {
                std::string reg = emit_expr(s->let_value);
                LocalSlot slot;
                slot.alloca_name = reg;
                slot.type = tc_.i64();
                locals_[s->let_name] = slot;
            }
            break;
        }
        case StmtKind::Expr:
            (void)emit_expr(s->expr);
            break;
        case StmtKind::Return: {
            if (s->expr) {
                std::string reg = emit_expr(s->expr);
                std::string ret_ty = current_ret_type_
                    ? tc_.render_llvm(current_ret_type_) : "i64";
                emit_line("  ret " + ret_ty + " " + reg);
            } else {
                emit_line("  ret void");
            }
            terminated_ = true;
            break;
        }
        case StmtKind::Defer:
            // v0.2: defer is not yet lowered; would require
            // constructing a cleanup chain.
            if (s->expr) (void)emit_expr(s->expr);
            break;
        case StmtKind::Break:
            // v0.2: requires loop context. Stub for now.
            break;
        case StmtKind::Continue:
            break;
        case StmtKind::Unsafe:
        case StmtKind::Block:
            (void)emit_block(s->block);
            break;
    }
}

std::string Emitter::emit_expr(ExprPtr e) {
    if (!e || terminated_) return "";
    switch (e->kind) {
        case ExprKind::IntLit: {
            std::string reg = fresh_reg();
            emit_line("  " + reg + " = add i64 " +
                      std::to_string(e->int_value) + ", 0");
            return reg;
        }
        case ExprKind::FloatLit: {
            std::string reg = fresh_reg();
            std::ostringstream oss;
            oss << "  " << reg << " = fadd double " << e->float_value
                << ", 0.0";
            emit_line(oss.str());
            return reg;
        }
        case ExprKind::StringLit: {
            return emit_string_literal(e->str_value);
        }
        case ExprKind::CharLit: {
            std::string reg = fresh_reg();
            emit_line("  " + reg + " = add i64 " +
                      std::to_string(e->int_value) + ", 0");
            return reg;
        }
        case ExprKind::BoolLit: {
            std::string reg = fresh_reg();
            emit_line("  " + reg + " = add i1 " +
                      std::to_string(e->int_value) + ", 0");
            return reg;
        }
        case ExprKind::Ident: {
            if (e->path.empty()) return "";
            auto it = locals_.find(e->path[0]);
            if (it != locals_.end()) {
                return it->second.alloca_name;
            }
            // Fall back: treat as zero.
            std::string reg = fresh_reg();
            emit_line("  " + reg + " = add i64 0, 0");
            return reg;
        }
        case ExprKind::Path: {
            // v0.2: path expressions are either variant constructors
            // or function references. We don't lower either yet.
            std::string reg = fresh_reg();
            emit_line("  " + reg + " = add i64 0, 0");
            return reg;
        }
        case ExprKind::Unary: {
            std::string operand = emit_expr(e->lhs);
            switch (e->unary_op) {
                case UnaryOp::Neg: {
                    std::string reg = fresh_reg();
                    emit_line("  " + reg + " = sub i64 0, " + operand);
                    return reg;
                }
                case UnaryOp::Not: {
                    std::string reg = fresh_reg();
                    emit_line("  " + reg + " = xor i1 " + operand +
                              ", true");
                    return reg;
                }
                case UnaryOp::BitNot: {
                    std::string reg = fresh_reg();
                    emit_line("  " + reg + " = xor i64 " + operand +
                              ", -1");
                    return reg;
                }
                case UnaryOp::Deref: {
                    std::string reg = fresh_reg();
                    emit_line("  " + reg + " = load i64, i64* " +
                              operand);
                    return reg;
                }
                case UnaryOp::Borrow:
                case UnaryOp::BorrowMut:
                case UnaryOp::Move:
                    // For v0.2, borrows and moves are no-ops at the
                    // LLVM level — the value is just passed through.
                    return operand;
            }
            return "";
        }
        case ExprKind::Binary: {
            std::string l = emit_expr(e->lhs);
            std::string r = emit_expr(e->rhs);
            std::string reg = fresh_reg();
            const char* op = "add";
            std::string ty = "i64";
            switch (e->binary_op) {
                case BinaryOp::Add:    op = "add";  break;
                case BinaryOp::Sub:    op = "sub";  break;
                case BinaryOp::Mul:    op = "mul";  break;
                case BinaryOp::Div:    op = "sdiv"; break;
                case BinaryOp::Mod:    op = "srem"; break;
                case BinaryOp::BitAnd: op = "and";  break;
                case BinaryOp::BitOr:  op = "or";   break;
                case BinaryOp::BitXor: op = "xor";  break;
                case BinaryOp::Shl:    op = "shl";  break;
                case BinaryOp::Shr:    op = "ashr"; break;
                case BinaryOp::And:    op = "and"; ty = "i1"; break;
                case BinaryOp::Or:     op = "or";  ty = "i1"; break;
                case BinaryOp::Eq:     op = "icmp eq"; ty = "i1"; break;
                case BinaryOp::Neq:    op = "icmp ne"; ty = "i1"; break;
                case BinaryOp::Lt:     op = "icmp slt"; ty = "i1"; break;
                case BinaryOp::Gt:     op = "icmp sgt"; ty = "i1"; break;
                case BinaryOp::Le:     op = "icmp sle"; ty = "i1"; break;
                case BinaryOp::Ge:     op = "icmp sge"; ty = "i1"; break;
            }
            if (e->binary_op >= BinaryOp::Eq && e->binary_op <= BinaryOp::Ge) {
                // ICMP form: %r = icmp eq i64 %l, %r
                emit_line("  " + reg + " = " + op + " i64 " + l + ", " + r);
            } else {
                emit_line("  " + reg + " = " + op + " " + ty + " " +
                          l + ", " + r);
            }
            return reg;
        }
        case ExprKind::Assign: {
            std::string lhs = emit_expr(e->lhs);
            std::string rhs = emit_expr(e->rhs);
            emit_line("  store i64 " + rhs + ", i64* " + lhs);
            return "";
        }
        case ExprKind::Call: {
            // v0.2: only direct calls to identifiers/paths.
            std::string callee_name;
            if (e->lhs && e->lhs->kind == ExprKind::Ident &&
                !e->lhs->path.empty()) {
                callee_name = std::string(intern_.get(e->lhs->path[0]));
            } else if (e->lhs && e->lhs->kind == ExprKind::Path &&
                       !e->lhs->path.empty()) {
                // Use the last component as the function name.
                callee_name = std::string(intern_.get(e->lhs->path.back()));
            } else {
                return "";
            }
            // For non-extern functions, use the mangled name.
            std::string mangled = "_tether_" + callee_name;
            std::string args;
            for (size_t i = 0; i < e->args.size(); ++i) {
                if (i) args += ", ";
                std::string arg = emit_expr(e->args[i]);
                args += "i64 " + arg;
            }
            std::string reg = fresh_reg();
            emit_line("  " + reg + " = call i64 @" + mangled + "(" +
                      args + ")");
            return reg;
        }
        case ExprKind::MethodCall: {
            (void)emit_expr(e->lhs);
            for (ExprPtr a : e->args) (void)emit_expr(a);
            return "";
        }
        case ExprKind::FieldAccess: {
            (void)emit_expr(e->lhs);
            return "";
        }
        case ExprKind::Index: {
            (void)emit_expr(e->lhs);
            (void)emit_expr(e->index);
            return "";
        }
        case ExprKind::Question: {
            return emit_expr(e->lhs);
        }
        case ExprKind::Block: {
            return emit_block(e->block);
        }
        case ExprKind::If: {
            std::string cond = emit_expr(e->cond);
            std::string then_label = fresh_label();
            std::string else_label = fresh_label();
            std::string end_label = fresh_label();
            emit_line("  br i1 " + cond + ", label %" + then_label +
                      ", label %" + else_label);

            // Then block.
            emit_line(then_label + ":");
            bool saved_term = terminated_;
            terminated_ = false;
            std::string then_val = emit_expr(e->then_branch);
            bool then_term = terminated_;
            if (!terminated_) {
                emit_line("  br label %" + end_label);
            }
            terminated_ = false;

            // Else block.
            emit_line(else_label + ":");
            std::string else_val;
            if (e->else_branch) {
                else_val = emit_expr(e->else_branch);
            }
            bool else_term = terminated_;
            if (!terminated_) {
                emit_line("  br label %" + end_label);
            }
            terminated_ = false;

            // End block.
            emit_line(end_label + ":");
            if (then_term && else_term) {
                terminated_ = true;
                return "";
            }
            // v0.2: if-else returns void if either branch is void.
            return then_val.empty() ? else_val : then_val;
        }
        case ExprKind::Match: {
            // v0.2: lower match as a sequence of comparisons. For now,
            // just emit the scrutinee and the first arm's body.
            (void)emit_expr(e->cond);
            if (!e->arms.empty()) {
                return emit_expr(e->arms[0].body);
            }
            return "";
        }
        case ExprKind::Loop: {
            std::string top = fresh_label();
            std::string end = fresh_label();
            emit_line("  br label %" + top);
            emit_line(top + ":");
            bool saved = terminated_;
            terminated_ = false;
            (void)emit_expr(e->body);
            if (!terminated_) {
                emit_line("  br label %" + top);
            }
            terminated_ = false;
            emit_line(end + ":");
            return "";
        }
        case ExprKind::While: {
            std::string top = fresh_label();
            std::string body_label = fresh_label();
            std::string end = fresh_label();
            emit_line("  br label %" + top);
            emit_line(top + ":");
            std::string cond = emit_expr(e->cond);
            emit_line("  br i1 " + cond + ", label %" + body_label +
                      ", label %" + end);
            emit_line(body_label + ":");
            bool saved = terminated_;
            terminated_ = false;
            (void)emit_expr(e->body);
            if (!terminated_) {
                emit_line("  br label %" + top);
            }
            terminated_ = false;
            emit_line(end + ":");
            return "";
        }
        case ExprKind::For: {
            (void)emit_expr(e->iterable);
            (void)emit_expr(e->body);
            return "";
        }
        case ExprKind::Return: {
            if (e->return_value) {
                std::string reg = emit_expr(e->return_value);
                std::string ret_ty = current_ret_type_
                    ? tc_.render_llvm(current_ret_type_) : "i64";
                emit_line("  ret " + ret_ty + " " + reg);
            } else {
                emit_line("  ret void");
            }
            terminated_ = true;
            return "";
        }
        case ExprKind::Break:
        case ExprKind::Continue:
            return "";
        case ExprKind::Defer:
            (void)emit_expr(e->lhs);
            return "";
        case ExprKind::Alloc: {
            if (e->alloc_value) return emit_expr(e->alloc_value);
            return "";
        }
        case ExprKind::Move:
        case ExprKind::Borrow:
            return emit_expr(e->lhs);
        case ExprKind::Unsafe:
            return emit_block(e->block);
        case ExprKind::Spawn:
            (void)emit_expr(e->body);
            return "";
        case ExprKind::Comptime:
            // Lower like a block — the optimizer will fold constants.
            return emit_block(e->block);
        case ExprKind::Reflect:
            // Compile-time reflection — no runtime code.
            return "";
        case ExprKind::Await:
            return emit_expr(e->lhs);
        case ExprKind::Tuple: {
            // v0.2: tuples are not fully supported; emit a placeholder.
            for (ExprPtr a : e->args) (void)emit_expr(a);
            return "";
        }
        case ExprKind::ArrayLit: {
            for (ExprPtr a : e->args) (void)emit_expr(a);
            return "";
        }
    }
    return "";
}

std::string Emitter::emit_string_literal(StrId str_id) {
    auto it = strings_.find(str_id);
    if (it != strings_.end()) {
        // Return a pointer to the global: bitcast the [N x i8]* to i8*.
        std::string reg = fresh_reg();
        emit_line("  " + reg + " = getelementptr [" +
                  std::to_string(intern_.get(str_id).size() + 1) +
                  " x i8], [" +
                  std::to_string(intern_.get(str_id).size() + 1) +
                  " x i8]* " + it->second + ", i64 0, i64 0");
        return reg;
    }
    std::string name = fresh_string();
    strings_[str_id] = name;
    // Emit a placeholder now; the actual constant will be emitted at
    // the top of the module.
    std::string reg = fresh_reg();
    emit_line("  " + reg + " = getelementptr [" +
              std::to_string(intern_.get(str_id).size() + 1) +
              " x i8], [" +
              std::to_string(intern_.get(str_id).size() + 1) +
              " x i8]* " + name + ", i64 0, i64 0");
    return reg;
}

void Emitter::reset_function_state() {
    next_reg_ = 1;
    next_label_ = 1;
    locals_.clear();
    entry_allocas_.clear();
    body_.clear();
    terminated_ = false;
    // Note: strings_ is NOT reset — string globals are module-level.
}

} // namespace tether::llvm
